language: ruby
cache: bundler
sudo: false
before_install:
  - gem update --system --conservative || (gem i "rubygems-update:~>2.7" --no-document && update_rubygems)
  - gem update bundler --conservative
rvm:
 - 2.0
 - 2.1
 - 2.2
 - 2.3
 - 2.4
 - 2.5
